eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  dashboard:
    path: /
  server:
    enableSelfPreservation: false
server:
  port: 8761
